# -*- coding: utf-8 -*-
"""24-09-04-hello-world.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpP-m8abrxIi0P6_DcGVrYqkvCCB1EKp
"""

print("Hello World!!")

print("Hello Pyton")

import pylab as py

x_deg = py.arange(-180, 180+1,)
x_rad = py.deg2rad(x_deg)
y = py.sin(x_rad)

py.plot(x_deg, y)

py.xlabel('x (deg)')
py.ylabel('sing(x)')
py.grid(True)